name: rebootimer 
base: core18
version: '1.2.1'
summary:  unload and test connection
description: |
  Use this snap to reboot rpi if internet connection drops.
  Also disable/enable influxdb and tsbt if cpu load is greater than 2.5
grade: devel
confinement: devmode

apps:      
  init:
    daemon: oneshot
    command: ./bin/enable.sh
 
  reboot:
    #daemon: oneshot
    #timer: "00:00~24:00/6" #reboot every 4 hours random
    command: ./bin/disable.sh
    plugs:
       - shutdown
  unload:
    daemon: oneshot #disable/enable influxdb and tsbt on high load
    timer: "00:00~24:00/288" #every 5 minutes random
    command: ./bin/unload.sh    

  reconnect: #shutdown modem
    daemon: oneshot
    timer: "00:00-24:00/96" #test connection every 15 min
    command: ./bin/reconnectInternet.sh
    plugs:
       - shutdown
       - network
       - network-bind
    
  speed-test:
    command: speed-test
    plugs: [network-bind]



architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
    
parts:
  init:
    plugin: dump
    source: https://github.com/tsbt-cfg/reboot/
    source-type: git
    override-stage: |  
       snapcraftctl stage
       chmod +x bin/enable.sh
       chmod +x bin/disable.sh
       chmod +x bin/unload.sh
       chmod +x bin/reconnectInternet.sh

    
    organize:
      enable.sh : bin/enable.sh
      disable.sh : bin/disable.sh
      unload.sh : bin/unload.sh
      reconnectInternet.sh : bin/reconnectInternet.sh
    prime:
      - bin/enable.sh
      - bin/disable.sh
      - bin/unload.sh
      - bin/reconnectInternet.sh

 # speed-test:
 #   source: https://github.com/tsbt-cfg/speed-test.git
 #   source-type: git
 #   plugin: npm
 #   npm-node-version: 15.9.0

    

  speed-test:
    plugin: nodejs
    node-packages: [speed-test@2.1.0]

    organize:
      '*': iSpeed/
    prime: [iSpeed]

